/* tslint:disable */
/* eslint-disable */
/**
 * Angelfish Data API
 * APIs to provide data for Angelfish
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { CurrencyCodes } from './currency-codes'

/**
 * Currency Object
 * @export
 * @interface Currency
 */
export interface Currency {
  /**
   * The full name of the Currency
   * @type {string}
   * @memberof Currency
   */
  name: string
  /**
   *
   * @type {CurrencyCodes}
   * @memberof Currency
   */
  code: CurrencyCodes
  /**
   * The Currency symbol
   * @type {string}
   * @memberof Currency
   */
  symbol: string
  /**
   * The country flag associated with the Currency
   * @type {string}
   * @memberof Currency
   */
  flag: string
}
