/* tslint:disable */
/* eslint-disable */
/**
 * Angelfish Data API
 * APIs to provide data for Angelfish
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { StatementTransaction } from './statement-transaction';

/**
 * 
 * @export
 * @interface ExtractTransactions200Response
 */
export interface ExtractTransactions200Response {
    /**
     * 
     * @type {Array<StatementTransaction>}
     * @memberof ExtractTransactions200Response
     */
    'transactions': Array<StatementTransaction>;
}

