/* tslint:disable */
/* eslint-disable */
/**
 * Angelfish Data API
 * APIs to provide data for Angelfish
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CurrencyCodes } from './currency-codes';

/**
 * Currency Response
 * @export
 * @interface HistoricalCurrencyExchangeRates
 */
export interface HistoricalCurrencyExchangeRates {
    /**
     * 
     * @type {CurrencyCodes}
     * @memberof HistoricalCurrencyExchangeRates
     */
    'currency': CurrencyCodes;
    /**
     * 
     * @type {CurrencyCodes}
     * @memberof HistoricalCurrencyExchangeRates
     */
    'base': CurrencyCodes;
    /**
     * 
     * @type {string}
     * @memberof HistoricalCurrencyExchangeRates
     */
    'start_date': string;
    /**
     * 
     * @type {string}
     * @memberof HistoricalCurrencyExchangeRates
     */
    'end_date': string;
    /**
     * An object where keys are dates (YYYY-MM-DD) and values are exchange rates.
     * @type {{ [key: string]: number; }}
     * @memberof HistoricalCurrencyExchangeRates
     */
    'rates': { [key: string]: number; };
}



