/* tslint:disable */
/* eslint-disable */
/**
 * Angelfish Data API
 * APIs to provide data for Angelfish
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Financial Institution
 * @export
 * @interface Institution
 */
export interface Institution {
    /**
     * The unique identifier of the Institution
     * @type {string}
     * @memberof Institution
     */
    'id': string;
    /**
     * The full name of the Institution
     * @type {string}
     * @memberof Institution
     */
    'name': string;
    /**
     * Base64 encoded PNG logo of the Institution
     * @type {string}
     * @memberof Institution
     */
    'logo'?: string;
    /**
     * The URL of the Institution
     * @type {string}
     * @memberof Institution
     */
    'url'?: string;
    /**
     * The countries where the Institution is available
     * @type {Array<string>}
     * @memberof Institution
     */
    'country_codes': Array<string>;
}

