/* tslint:disable */
/* eslint-disable */
/**
 * Angelfish Data API
 * APIs to provide data for Angelfish
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { CurrencyCodes } from './currency-codes'

/**
 * Latest Exchange Rate Response
 * @export
 * @interface LatestCurrencyExchangeRates
 */
export interface LatestCurrencyExchangeRates {
  /**
   *
   * @type {CurrencyCodes}
   * @memberof LatestCurrencyExchangeRates
   */
  base: CurrencyCodes
  /**
   * An object where keys are ISO4217 Currency Codes and values are latest exchange rates for that currency.
   * @type {{ [key: string]: number; }}
   * @memberof LatestCurrencyExchangeRates
   */
  rates: { [key: string]: number }
}
