/* tslint:disable */

/**
 * Angelfish Data API
 * APIs to provide data for Angelfish
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Extracted Statement Transaction
 * @export
 * @interface StatementTransaction
 */
export interface StatementTransaction {
  /**
   * The date of the transaction.
   * @type {string}
   * @memberof StatementTransaction
   */
  date: string
  /**
   * The primary description or payee of the transaction.
   * @type {string}
   * @memberof StatementTransaction
   */
  name: string
  /**
   * The amount for the transaction. A credit (income) amount should be a positive number. A debit (expense) amount should be a negative number.
   * @type {number}
   * @memberof StatementTransaction
   */
  amount: number
  /**
   * An optional, more detailed description of the transaction if available.
   * @type {string}
   * @memberof StatementTransaction
   */
  memo?: string
}
