import { app, BrowserWindow, Menu, net, protocol } from 'electron'
import path from 'path'
import { updateElectronApp } from 'update-electron-app'

import { setupMainCommands } from './commands'
import { getMainLogger } from './logger'
import { menu } from './menu'
import { Environment } from './utils/environment'
import { ProcessIDs } from './windows/process-ids'
import { WindowManager } from './windows/windows-manager'

const logger = getMainLogger('main')

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const APP_WINDOW_WEBPACK_ENTRY: string
declare const WORKER_WINDOW_WEBPACK_ENTRY: string

/**
 * Setup Autoupdater
 */

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
// eslint-disable-next-line @typescript-eslint/no-require-imports
if (require('electron-squirrel-startup')) {
  app.quit()
}

if (Environment.isProduction && !Environment.isLinux) {
  updateElectronApp({
    repo: 'angelfishapp/desktop-releases',
    updateInterval: '1 hour',
    logger,
  })
}

// Alert developer if overriding environment with flag
if (Environment.nodeEnvironment !== Environment.environment) {
  logger.info(`Overriding Environment to ${Environment.environment}`)
}

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', () => {
  logger.debug('Electron Ready...')

  // Override file:// protocol for serving static assets in distribution
  protocol.handle('file', (request) => {
    const url = request.url.substring(7) /* all urls start with 'file://' */
    if (url.includes('/assets/')) {
      // Only rewrite files looking for assets folder
      const assetUrl = url.split('/assets/')[1]
      const newPath = path.normalize(`${__dirname}/../renderer/assets/${assetUrl}`)
      logger.debug(`Intercepted File protocol: url=${url}, newPath=${newPath}`)
      return net.fetch(`file://${newPath}`)
    }
    return net.fetch(`file://${url}`)
  })

  // Create Worker Window
  WindowManager.createProcessWindow(ProcessIDs.WORKER, WORKER_WINDOW_WEBPACK_ENTRY, true, true)
  // Create App Window
  WindowManager.createMainAppWindow(APP_WINDOW_WEBPACK_ENTRY)

  // Set Application Menu
  Menu.setApplicationMenu(menu)
  // Register Commands & Event Handlers
  setupMainCommands()
})

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit()
  }
})

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    WindowManager.createProcessWindow(ProcessIDs.WORKER, WORKER_WINDOW_WEBPACK_ENTRY, true, true)
    WindowManager.createMainAppWindow(APP_WINDOW_WEBPACK_ENTRY)
  }
})
