/* tslint:disable */
/* eslint-disable */
/**
 * Angelfish Data API
 * APIs to provide data for Angelfish
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export * from './api/aiapi';
export * from './api/currencies-api';
export * from './api/institutions-api';

