/* tslint:disable */
/* eslint-disable */
/**
 * Angelfish API
 * Authentication APIs to provide secure access to Angelfish services
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AuthenticationRequestOneOfResponse } from './authentication-request-one-of-response';

/**
 * 
 * @export
 * @interface AuthenticationRequestOneOf
 */
export interface AuthenticationRequestOneOf {
    /**
     * The authentication provider used to authenticate the user
     * @type {string}
     * @memberof AuthenticationRequestOneOf
     */
    'provider': AuthenticationRequestOneOfProviderEnum;
    /**
     * The session ID
     * @type {string}
     * @memberof AuthenticationRequestOneOf
     */
    'session_id': string;
    /**
     * 
     * @type {AuthenticationRequestOneOfResponse}
     * @memberof AuthenticationRequestOneOf
     */
    'response': AuthenticationRequestOneOfResponse;
}

export const AuthenticationRequestOneOfProviderEnum = {
    OobCode: 'oob_code'
} as const;

export type AuthenticationRequestOneOfProviderEnum = typeof AuthenticationRequestOneOfProviderEnum[keyof typeof AuthenticationRequestOneOfProviderEnum];


