/* tslint:disable */
/* eslint-disable */
/**
 * Angelfish API
 * Authentication APIs to provide secure access to Angelfish services
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AuthenticationRequestOneOfResponse
 */
export interface AuthenticationRequestOneOfResponse {
    /**
     * The out-of-band code
     * @type {string}
     * @memberof AuthenticationRequestOneOfResponse
     */
    'oob_code': string;
}

