/* tslint:disable */
/* eslint-disable */
/**
 * Angelfish API
 * Authentication APIs to provide secure access to Angelfish services
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { AuthenticationRequestOneOf } from './authentication-request-one-of'
// May contain unused imports in some cases
// @ts-ignore
import type { AuthenticationRequestOneOfResponse } from './authentication-request-one-of-response'

/**
 * @type AuthenticationRequest
 * The authentication request schema
 * @export
 */
export type AuthenticationRequest = AuthenticationRequestOneOf
