/* tslint:disable */
/* eslint-disable */
/**
 * Angelfish API
 * Authentication APIs to provide secure access to Angelfish services
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GetOOBCodeRequest
 */
export interface GetOOBCodeRequest {
    /**
     * The email address to send the code to
     * @type {string}
     * @memberof GetOOBCodeRequest
     */
    'email': string;
}

