/**
 * Angelfish API
 * Authentication APIs to provide secure access to Angelfish services
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * The authentication token schema
 * @export
 * @interface TokenResponse
 */
export interface TokenResponse {
  /**
   * The Base64 encoded JWT Token for the authenticated user
   * @type {string}
   * @memberof TokenResponse
   */
  token: string
  /**
   * The Refresh Token for the authenticated user
   * @type {string}
   * @memberof TokenResponse
   */
  refresh_token: string
}
