/* tslint:disable */
 
/**
 * Angelfish API
 * Authentication APIs to provide secure access to Angelfish services
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface UserProfileUpdate
 */
export interface UserProfileUpdate {
  /**
   * The user\'s first name
   * @type {string}
   * @memberof UserProfileUpdate
   */
  first_name?: string
  /**
   * The user\'s last name
   * @type {string}
   * @memberof UserProfileUpdate
   */
  last_name?: string
  /**
   * The user\'s E.164 formatted phone number
   * @type {string}
   * @memberof UserProfileUpdate
   */
  phone_number?: string
  /**
   * The user\'s Base64 Encoded 100x100 PNG avatar
   * @type {string}
   * @memberof UserProfileUpdate
   */
  avatar?: string
}
