/* tslint:disable */

/**
 * Angelfish API
 * Authentication APIs to provide secure access to Angelfish services
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * The user profile schema
 * @export
 * @interface UserProfile
 */
export interface UserProfile {
  /**
   * The user\'s ID
   * @type {string}
   * @memberof UserProfile
   */
  id: string
  /**
   * The user\'s email address
   * @type {string}
   * @memberof UserProfile
   */
  email: string
  /**
   * The date the user was created
   * @type {string}
   * @memberof UserProfile
   */
  created_on: string
  /**
   * The date the user was last updated
   * @type {string}
   * @memberof UserProfile
   */
  modified_on: string
  /**
   * The user\'s first name
   * @type {string}
   * @memberof UserProfile
   */
  first_name?: string
  /**
   * The user\'s last name
   * @type {string}
   * @memberof UserProfile
   */
  last_name?: string
  /**
   * The user\'s E.164 formatted phone number
   * @type {string}
   * @memberof UserProfile
   */
  phone_number?: string
  /**
   * The user\'s Base64 Encoded 100x100 PNG avatar
   * @type {string}
   * @memberof UserProfile
   */
  avatar?: string
  /**
   * Is the user disabled
   * @type {boolean}
   * @memberof UserProfile
   */
  is_disabled: boolean
}
