/* tslint:disable */
/* eslint-disable */
/**
 * Angelfish Data API
 * APIs to provide data for Angelfish
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ExtractTransactions200Response } from '../models';
/**
 * AIApi - axios parameter creator
 * @export
 */
export const AIApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Extract Transactions from images (JPG, PNG, HEIC) and PDFs using AI
         * @param {File} [file] File to upload (JPG, PNG, HEIC, PDF). Must be under 10MB
         * @param {string} [startDate] Start date of statement (YYYY-MM-DD) to help AI infer full YYYY-MM-DD dates if not available on statement itself
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        extractTransactions: async (file?: File, startDate?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/ai/extract-transactions`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new ((configuration && configuration.formDataCtor) || FormData)();

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


            if (file !== undefined) { 
                localVarFormParams.append('file', file as any);
            }
    
            if (startDate !== undefined) { 
                localVarFormParams.append('start_date', startDate as any);
            }
    
    
            localVarHeaderParameter['Content-Type'] = 'multipart/form-data';
    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams;

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AIApi - functional programming interface
 * @export
 */
export const AIApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AIApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Extract Transactions from images (JPG, PNG, HEIC) and PDFs using AI
         * @param {File} [file] File to upload (JPG, PNG, HEIC, PDF). Must be under 10MB
         * @param {string} [startDate] Start date of statement (YYYY-MM-DD) to help AI infer full YYYY-MM-DD dates if not available on statement itself
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async extractTransactions(file?: File, startDate?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ExtractTransactions200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.extractTransactions(file, startDate, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AIApi.extractTransactions']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AIApi - factory interface
 * @export
 */
export const AIApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AIApiFp(configuration)
    return {
        /**
         * 
         * @summary Extract Transactions from images (JPG, PNG, HEIC) and PDFs using AI
         * @param {File} [file] File to upload (JPG, PNG, HEIC, PDF). Must be under 10MB
         * @param {string} [startDate] Start date of statement (YYYY-MM-DD) to help AI infer full YYYY-MM-DD dates if not available on statement itself
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        extractTransactions(file?: File, startDate?: string, options?: RawAxiosRequestConfig): AxiosPromise<ExtractTransactions200Response> {
            return localVarFp.extractTransactions(file, startDate, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AIApi - object-oriented interface
 * @export
 * @class AIApi
 * @extends {BaseAPI}
 */
export class AIApi extends BaseAPI {
    /**
     * 
     * @summary Extract Transactions from images (JPG, PNG, HEIC) and PDFs using AI
     * @param {File} [file] File to upload (JPG, PNG, HEIC, PDF). Must be under 10MB
     * @param {string} [startDate] Start date of statement (YYYY-MM-DD) to help AI infer full YYYY-MM-DD dates if not available on statement itself
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AIApi
     */
    public extractTransactions(file?: File, startDate?: string, options?: RawAxiosRequestConfig) {
        return AIApiFp(this.configuration).extractTransactions(file, startDate, options).then((request) => request(this.axios, this.basePath));
    }
}

