# Main workflow to package and release a new build of the Angelfish
# Electron.js application using Electron Forge

name: Package and Release

# Trigger action if commit contains a v* tag
on:
  push:
    branches:
      - main
      - launch
    # tags:
    #  - v*

jobs:
  build:
    name: Build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # macos-13 is last intel macos version, add back windows-latest
        os: [macos-latest, ubuntu-latest, macos-13]
      fail-fast: false

    # Set GITHUB_TOKEN permissions to allow release creation during publish step
    permissions:
      contents: write

    steps:
      # Setup Environment

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup-env

      - name: Build Workspace Dependency packages
        run: yarn build:packages

      - name: Add MacOS Certificates
        if: matrix.os == 'macos-latest' || matrix.os == 'macos-13'
        run: chmod +x ./packages/electron/resources/build/macos/add-osx-cert.sh && ./packages/electron/resources/build/macos/add-osx-cert.sh
        env:
          CERTIFICATE_OSX_APPLICATION: ${{ secrets.CERTIFICATE_OSX_APPLICATION }}
          CERTIFICATE_OSX_PASSWORD: ${{ secrets.CERTIFICATE_OSX_PASSWORD }}

      - name: Add Windows Certificate
        if: matrix.os == 'windows-latest'
        id: write_file
        uses: timheuer/base64-to-file@v1
        with:
          fileName: 'win-certificate.pfx'
          encodedString: ${{ secrets.WINDOWS_PFX_FILE }}

      # Package App

      - name: Make
        run: yarn make
        env:
          OSX_SIGN_IDENTITY: ${{ secrets.OSX_SIGN_IDENTITY }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}

      # Create New Release for App

      - name: Publish
        run: yarn publish
        env:
          OSX_SIGN_IDENTITY: ${{ secrets.OSX_SIGN_IDENTITY }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
